/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'user' : IDL.Principal,
  'address' : IDL.Text,
  'requestedDate' : IDL.Text,
  'serviceId' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePerVisit' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserBookings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'requestBooking' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'user' : IDL.Principal,
    'address' : IDL.Text,
    'requestedDate' : IDL.Text,
    'serviceId' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePerVisit' : IDL.Nat,
  });
  
  return IDL.Service({
    'addService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingRequest)], ['query']),
    'getService' : IDL.Func([IDL.Nat], [Service], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'requestBooking' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };