/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : bigint,
  'status' : string,
  'user' : Principal,
  'address' : string,
  'requestedDate' : string,
  'serviceId' : bigint,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'pricePerVisit' : bigint,
}
export interface _SERVICE {
  'addService' : ActorMethod<[string, string, bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<BookingRequest>>,
  'getService' : ActorMethod<[bigint], Service>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserBookings' : ActorMethod<[Principal], Array<BookingRequest>>,
  'requestBooking' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];